const KEY_EVENTS = "countdown.events.v1";
const KEY_MODE = "countdown.mode.v1";

const SEED = [
  { id: "half-marathon", title: "Half Marathon", category: "run", date: "2026-11-29" },
  { id: "placements", title: "Placement Season", category: "career", date: "2026-11-30", endDate: "2026-12-03" },
];
const ICONS = { run: "🏃", career: "💼", any: "🎯" };

const $ = (id) => document.getElementById(id);
let events = load(KEY_EVENTS, SEED);
let mode = load(KEY_MODE, "gentle");
let editingId = null;
let widgetScript = "";

function load(key, fallback) {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch (e) {
    return fallback;
  }
}
function save() {
  try {
    localStorage.setItem(KEY_EVENTS, JSON.stringify(events));
    localStorage.setItem(KEY_MODE, JSON.stringify(mode));
  } catch (e) { /* private mode etc: keep working in memory */ }
}

function fmtDate(key) {
  const [y, m, d] = key.split("-").map(Number);
  return new Date(y, m - 1, d).toLocaleDateString("en-GB", {
    weekday: "short", day: "numeric", month: "short", year: "numeric",
  });
}

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text != null) n.textContent = text;
  return n;
}

function render() {
  const now = new Date();
  $("today").textContent = now.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" });

  document.querySelectorAll(".seg button").forEach((b) => {
    const on = b.dataset.mode === mode;
    b.classList.toggle("on", on);
    b.setAttribute("aria-checked", on);
  });

  const ranked = rankEvents(events, now);
  $("quote").textContent = pickQuote(QUOTES, mode, ranked[0], now);
  $("quote-meta").textContent = ranked.length
    ? `Today's push for ${ranked[0].ev.title}`
    : "Nothing on the clock";

  const list = $("events");
  list.replaceChildren();
  const all = events
    .map((ev) => ({ ev, st: eventStatus(ev, now) }))
    .sort((a, b) => {
      const ra = ranked.indexOf(ranked.find((r) => r.ev.id === a.ev.id));
      const rb = ranked.indexOf(ranked.find((r) => r.ev.id === b.ev.id));
      if (ra < 0 && rb < 0) return a.st.days - b.st.days;
      if (ra < 0) return 1;
      if (rb < 0) return -1;
      return ra - rb;
    });

  if (!all.length) list.append(el("p", "empty", "No countdowns yet. Add one below."));

  all.forEach(({ ev, st }) => {
    const h = headline(st);
    const card = el("button", `card ${st.state}`);
    card.type = "button";
    card.append(el("span", "icon", ICONS[ev.category] || ICONS.any));
    const mid = el("span", "mid");
    mid.append(el("span", "name", ev.title));
    const when = ev.endDate && ev.endDate !== ev.date
      ? `${fmtDate(ev.date)} to ${fmtDate(ev.endDate)}`
      : fmtDate(ev.date);
    mid.append(el("span", "when", st.state === "upcoming" && ev.endDate ? `Starts ${when}` : when));
    card.append(mid);
    const num = el("span", "num");
    num.append(el("span", "big", h.big), el("span", "small", h.small));
    card.append(num);
    card.addEventListener("click", () => openDialog(ev));
    list.append(card);
  });

  buildWidgetScript(ranked);
}

// Build the Scriptable script ahead of time so the copy tap can stay inside
// the user gesture (Safari rejects clipboard writes after an await).
async function buildWidgetScript() {
  try {
    const [core, tpl] = await Promise.all([
      fetch("core.js").then((r) => r.text()),
      fetch("widget.template.js").then((r) => r.text()),
    ]);
    widgetScript =
      "// Countdown widget. Generated by the Countdown web app.\n" +
      `const CONFIG = ${JSON.stringify({ events, mode })};\n` +
      `const QUOTES = ${JSON.stringify(QUOTES)};\n` +
      core + "\n" + tpl;
  } catch (e) {
    widgetScript = "";
  }
}

async function copyScript() {
  const hint = $("copy-hint");
  if (!widgetScript) await buildWidgetScript();
  try {
    await navigator.clipboard.writeText(widgetScript);
    hint.textContent = "Copied. Now paste it into a new Scriptable script.";
  } catch (e) {
    const ta = $("script");
    ta.hidden = false;
    ta.value = widgetScript;
    ta.focus();
    ta.select();
    hint.textContent = "Couldn't copy automatically. Select all in the box below, copy it, and paste into Scriptable.";
  }
}

// ---- add / edit dialog ----
const dlg = $("dlg");
const form = $("form");

function openDialog(ev) {
  editingId = ev ? ev.id : null;
  $("dlg-title").textContent = ev ? "Edit countdown" : "New countdown";
  $("del").hidden = !ev;
  form.title.value = ev ? ev.title : "";
  form.category.value = ev ? ev.category : "any";
  form.date.value = ev ? ev.date : "";
  form.endDate.value = ev && ev.endDate ? ev.endDate : "";
  dlg.showModal();
}

form.addEventListener("submit", () => {
  const rec = {
    id: editingId || "e" + Date.now(),
    title: form.title.value.trim(),
    category: form.category.value,
    date: form.date.value,
  };
  if (form.endDate.value && form.endDate.value >= rec.date) rec.endDate = form.endDate.value;
  events = editingId ? events.map((e) => (e.id === editingId ? rec : e)) : events.concat(rec);
  save();
  render();
});
$("cancel").addEventListener("click", () => dlg.close());
$("del").addEventListener("click", () => {
  events = events.filter((e) => e.id !== editingId);
  save();
  dlg.close();
  render();
});
$("add").addEventListener("click", () => openDialog(null));
$("copy").addEventListener("click", copyScript);
document.querySelectorAll(".seg button").forEach((b) =>
  b.addEventListener("click", () => {
    mode = b.dataset.mode;
    save();
    render();
  })
);

// Keep the number current: on resume, and at midnight if left open.
document.addEventListener("visibilitychange", () => { if (!document.hidden) render(); });
function scheduleMidnight() {
  const n = new Date();
  const next = new Date(n.getFullYear(), n.getMonth(), n.getDate() + 1, 0, 0, 5);
  setTimeout(() => { render(); scheduleMidnight(); }, next - n);
}
scheduleMidnight();

render();

if ("serviceWorker" in navigator) {
  navigator.serviceWorker.register("sw.js").catch(() => {});
}
